---
name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    container:
      image: voegelas/debian-devel
      options: --user root

    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt-get install -y libmaxminddb-dev
          cpanm --quiet --notest --installdeps .
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          perl Makefile.PL
          cover -test -report coveralls
