---
name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    container:
      image: voegelas/perl-devel-cover
    steps:
      - uses: actions/checkout@v3
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: |
          apt-get install -y libmaxminddb-dev
          cpanm --quiet --notest --installdeps .
      - name: Run tests
        run: |
          perl Makefile.PL
          cover -test
